// <auto-generated />
namespace Metabol.DbModels.Migrations.ApplicationDbContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Remigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201608031548152_Remigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
