//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Metabol.Util.DB2
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetabolicNetworkDBContext : DbContext
    {
        public MetabolicNetworkDBContext()
            : base("name=MetabolicNetworkDBContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AnnotationQualifier> AnnotationQualifiers { get; set; }
        public virtual DbSet<attribute_names> attribute_names { get; set; }
        public virtual DbSet<attribute_values> attribute_values { get; set; }
        public virtual DbSet<Author> Authors { get; set; }
        public virtual DbSet<basic_molecules> basic_molecules { get; set; }
        public virtual DbSet<chromosome> chromosomes { get; set; }
        public virtual DbSet<common_molecules> common_molecules { get; set; }
        public virtual DbSet<common_species> common_species { get; set; }
        public virtual DbSet<Compartment> Compartments { get; set; }
        public virtual DbSet<CompartmentType> CompartmentTypes { get; set; }
        public virtual DbSet<Constraint> Constraints { get; set; }
        public virtual DbSet<Cycle> Cycles { get; set; }
        public virtual DbSet<DataSource> DataSources { get; set; }
        public virtual DbSet<DesignedBy> DesignedBies { get; set; }
        public virtual DbSet<ec_number_name_lookups> ec_number_name_lookups { get; set; }
        public virtual DbSet<ec_numbers> ec_numbers { get; set; }
        public virtual DbSet<entity_name_lookups> entity_name_lookups { get; set; }
        public virtual DbSet<Event> Events { get; set; }
        public virtual DbSet<EventAssignment> EventAssignments { get; set; }
        public virtual DbSet<EventDelay> EventDelays { get; set; }
        public virtual DbSet<EventTrigger> EventTriggers { get; set; }
        public virtual DbSet<FunctionDefinition> FunctionDefinitions { get; set; }
        public virtual DbSet<gene_encodings> gene_encodings { get; set; }
        public virtual DbSet<gene_products> gene_products { get; set; }
        public virtual DbSet<gene> genes { get; set; }
        public virtual DbSet<go_terms> go_terms { get; set; }
        public virtual DbSet<GONodeCode> GONodeCodes { get; set; }
        public virtual DbSet<InitialAssignment> InitialAssignments { get; set; }
        public virtual DbSet<KineticLaw> KineticLaws { get; set; }
        public virtual DbSet<MapModelsPathway> MapModelsPathways { get; set; }
        public virtual DbSet<MapReactionECNumber> MapReactionECNumbers { get; set; }
        public virtual DbSet<MapReactionsProcessEntity> MapReactionsProcessEntities { get; set; }
        public virtual DbSet<MapSpeciesMolecularEntity> MapSpeciesMolecularEntities { get; set; }
        public virtual DbSet<MetaboliteReactionCount> MetaboliteReactionCounts { get; set; }
        public virtual DbSet<MetaboliteReactionStoichiometry> MetaboliteReactionStoichiometries { get; set; }
        public virtual DbSet<Model> Models { get; set; }
        public virtual DbSet<ModelLayout> ModelLayouts { get; set; }
        public virtual DbSet<ModelMetadata> ModelMetadatas { get; set; }
        public virtual DbSet<ModelOrganism> ModelOrganism { get; set; }
        public virtual DbSet<molecular_entities> molecular_entities { get; set; }
        public virtual DbSet<molecular_entity_names> molecular_entity_names { get; set; }
        public virtual DbSet<molecular_entity_types> molecular_entity_types { get; set; }
        public virtual DbSet<name_types> name_types { get; set; }
        public virtual DbSet<OLD_external_database_links> OLD_external_database_links { get; set; }
        public virtual DbSet<OLD_external_databases> OLD_external_databases { get; set; }
        public virtual DbSet<organism_groups> organism_groups { get; set; }
        public virtual DbSet<organism> organisms { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<pathway_groups> pathway_groups { get; set; }
        public virtual DbSet<pathway_links> pathway_links { get; set; }
        public virtual DbSet<pathway_processes> pathway_processes { get; set; }
        public virtual DbSet<pathway_types> pathway_types { get; set; }
        public virtual DbSet<pathway> pathways { get; set; }
        public virtual DbSet<process_entities> process_entities { get; set; }
        public virtual DbSet<process_entity_roles> process_entity_roles { get; set; }
        public virtual DbSet<process> processes { get; set; }
        public virtual DbSet<protein> proteins { get; set; }
        public virtual DbSet<Reaction> Reactions { get; set; }
        public virtual DbSet<ReactionBound> ReactionBounds { get; set; }
        public virtual DbSet<ReactionSpecy> ReactionSpecies { get; set; }
        public virtual DbSet<ReactionSpeciesRole> ReactionSpeciesRoles { get; set; }
        public virtual DbSet<rna_types> rna_types { get; set; }
        public virtual DbSet<rna> rnas { get; set; }
        public virtual DbSet<Rule> Rules { get; set; }
        public virtual DbSet<RuleType> RuleTypes { get; set; }
        public virtual DbSet<Sbase> Sbases { get; set; }
        public virtual DbSet<Species> Species { get; set; }
        public virtual DbSet<SpeciesType> SpeciesTypes { get; set; }
        public virtual DbSet<StoichiometryMath> StoichiometryMaths { get; set; }
        public virtual DbSet<Unit> Units { get; set; }
        public virtual DbSet<UnitDefinition> UnitDefinitions { get; set; }
        public virtual DbSet<viewState> viewStates { get; set; }
        public virtual DbSet<BlockedReaction> BlockedReactions { get; set; }
        public virtual DbSet<catalyze> catalyzes { get; set; }
        public virtual DbSet<chromosome_bands> chromosome_bands { get; set; }
        public virtual DbSet<chromosomes_pathcase> chromosomes_pathcase { get; set; }
        public virtual DbSet<CompartmentClass> CompartmentClasses { get; set; }
        public virtual DbSet<CycleConnection> CycleConnections { get; set; }
        public virtual DbSet<CycleReaction> CycleReactions { get; set; }
        public virtual DbSet<ec_go> ec_go { get; set; }
        public virtual DbSet<ec_go_orig> ec_go_orig { get; set; }
        public virtual DbSet<entity_graph_nodes> entity_graph_nodes { get; set; }
        public virtual DbSet<external_database_links> external_database_links { get; set; }
        public virtual DbSet<external_database_urls> external_database_urls { get; set; }
        public virtual DbSet<external_databases> external_databases { get; set; }
        public virtual DbSet<go_annotation_pathways> go_annotation_pathways { get; set; }
        public virtual DbSet<go_pathway_annotation_counts> go_pathway_annotation_counts { get; set; }
        public virtual DbSet<go_pathway_group_annotation_counts> go_pathway_group_annotation_counts { get; set; }
        public virtual DbSet<go_terms_hierarchy> go_terms_hierarchy { get; set; }
        public virtual DbSet<MapSbaseGO> MapSbaseGOes { get; set; }
        public virtual DbSet<process_graph_nodes> process_graph_nodes { get; set; }
    }
}
