// <auto-generated />
namespace Metabol.Util.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MetaboliteReaction : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MetaboliteReaction));
        
        string IMigrationMetadata.Id
        {
            get { return "201510241602271_MetaboliteReaction"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
