// <auto-generated />
namespace Metabol.DbModels.Migrations.MetabolicNetworkContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Remigrate : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remigrate));
        
        string IMigrationMetadata.Id
        {
            get { return "201608031548488_Remigrate"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
