// <auto-generated />

using System.CodeDom.Compiler;
using System.Data.Entity.Migrations.Infrastructure;
using System.Resources;

namespace Metabol.DbModels.Migrations
{
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Bilmiyoruzk : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Bilmiyoruzk));
        
        string IMigrationMetadata.Id
        {
            get { return "201606242119411_Bilmiyoruzk"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
